---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: apt-key add
  ansible.builtin.apt_key:
    keyring: "{{ item.keyring }}"
    url: "{{ item.url }}"
    id: "{{ item.id }}"
    state: "{{ item.state }}"
  loop: "{{ _apt_key[postgres_release] }}"
  register: result
  until: result is succeeded

- name: apt-add-repository
  ansible.builtin.apt_repository:
    filename: "{{ item.filename }}"
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode | default('0644') }}"
  loop: "{{ _apt_repository[postgres_release] }}"
  register: result
  until: result is succeeded

- name: apt-get install postgresql-common
  ansible.builtin.apt:
    name: "postgresql-common"
    state: "present"
  register: result
  until: result is succeeded

- name: create_main_cluster = false
  ini_file:
    path: "/etc/postgresql-common/createcluster.conf"
    section: ""
    option: "create_main_cluster"
    value: "false"
    mode: "0644"
    state: "present"

- name: apt-get install
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ _apt[postgres_release] }}"
  register: result
  until: result is succeeded
  notify:
    - postgres | systemctl restart postgresql.service
